package com.htc.hibernate.pojo;

// Generated 1 Jul, 2015 9:39:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HolonManager generated by hbm2java
 */
public class HolonManager implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Set<?> holonObjects = new HashSet<Object>(0);

	public HolonManager() {
	}

	public HolonManager(int id) {
		this.id = id;
	}

	public HolonManager(int id, String name, Set<?> holonObjects) {
		this.id = id;
		this.name = name;
		this.holonObjects = holonObjects;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<?> getHolonObjects() {
		return this.holonObjects;
	}

	public void setHolonObjects(Set<?> holonObjects) {
		this.holonObjects = holonObjects;
	}

}
