package com.htc.hibernate.pojo;

/**
 * HolonElement generated by hbm2java
 */
public class HolonElement implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private HolonElementState holonElementState;
	private HolonElementType holonElementType;
	private HolonObject holonObject;
	private String usage;
	private Integer currentCapacity;
	private Boolean currentEnergyStatus;
	private byte[] history;

	public HolonElement() {
	}

	public HolonElement(int id) {
		this.id = id;
	}

	public HolonElement(int id, HolonElementState holonElementState,
			HolonElementType holonElementType, HolonObject holonObject,
			String usage, Integer currentCapacity, Boolean currentEnergyStatus,
			byte[] history) {
		this.id = id;
		this.holonElementState = holonElementState;
		this.holonElementType = holonElementType;
		this.holonObject = holonObject;
		this.usage = usage;
		this.currentCapacity = currentCapacity;
		this.currentEnergyStatus = currentEnergyStatus;
		this.history = history;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HolonElementState getHolonElementState() {
		return this.holonElementState;
	}

	public void setHolonElementState(HolonElementState holonElementState) {
		this.holonElementState = holonElementState;
	}

	public HolonElementType getHolonElementType() {
		return this.holonElementType;
	}

	public void setHolonElementType(HolonElementType holonElementType) {
		this.holonElementType = holonElementType;
	}

	public HolonObject getHolonObject() {
		return this.holonObject;
	}

	public void setHolonObject(HolonObject holonObject) {
		this.holonObject = holonObject;
	}

	public String getUsage() {
		return this.usage;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

	public Integer getCurrentCapacity() {
		return this.currentCapacity;
	}

	public void setCurrentCapacity(Integer currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public Boolean getCurrentEnergyStatus() {
		return this.currentEnergyStatus;
	}

	public void setCurrentEnergyStatus(Boolean currentEnergyStatus) {
		this.currentEnergyStatus = currentEnergyStatus;
	}

	public byte[] getHistory() {
		return this.history;
	}

	public void setHistory(byte[] history) {
		this.history = history;
	}

}
