package com.htc.hibernate.pojo;
import java.util.HashSet;
import java.util.Set;

/**
 * HolonElementType generated by hbm2java
 */
public class HolonElementType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Integer maxCapacity;
	private Integer minCapacity;
	private Boolean producer;
	private Set<?> holonElements = new HashSet<Object>(0);

	public HolonElementType() {
	}

	public HolonElementType(int id) {
		this.id = id;
	}

	public HolonElementType(int id, String name, Integer maxCapacity,
			Integer minCapacity, Set<?> holonElements,Boolean producer) {
		this.id = id;
		this.name = name;
		this.maxCapacity = maxCapacity;
		this.minCapacity = minCapacity;
		this.holonElements = holonElements;
		this.setProducer(producer);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMaxCapacity() {
		return this.maxCapacity;
	}

	public void setMaxCapacity(Integer maxCapacity) {
		this.maxCapacity = maxCapacity;
	}

	public Integer getMinCapacity() {
		return this.minCapacity;
	}

	public void setMinCapacity(Integer minCapacity) {
		this.minCapacity = minCapacity;
	}

	public Set<?> getHolonElements() {
		return this.holonElements;
	}

	public void setHolonElements(Set<?> holonElements) {
		this.holonElements = holonElements;
	}

	public Boolean getProducer() {
		return producer;
	}

	public void setProducer(Boolean producer) {
		this.producer = producer;
	}

}
