package com.htc.hibernate.pojo;
// Generated 16 Aug, 2015 3:28:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Holon generated by hbm2java
 */
public class Holon implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String color;
	private Set<?> holonCoordinators = new HashSet<Object>(0);
	private Set<?> powerLines = new HashSet<Object>(0);

	public Holon() {
	}

	public Holon(int id) {
		this.id = id;
	}

	public Holon(int id, String name, String color, Set<?> holonCoordinators, Set<?> powerLines) {
		this.id = id;
		this.name = name;
		this.color = color;
		this.holonCoordinators = holonCoordinators;
		this.setPowerLines(powerLines);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set<?> getHolonCoordinators() {
		return this.holonCoordinators;
	}

	public void setHolonCoordinators(Set<?> holonCoordinators) {
		this.holonCoordinators = holonCoordinators;
	}

	public Set<?> getPowerLines() {
		return powerLines;
	}

	public void setPowerLines(Set<?> powerLines) {
		this.powerLines = powerLines;
	}

}
