package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HolonCoordinator generated by hbm2java
 */
public class HolonCoordinator implements java.io.Serializable {

	private int id;
	private Holon holon;
	private LatLng latLng;
	private String name;
	private Set holonObjects = new HashSet(0);

	public HolonCoordinator() {
	}

	public HolonCoordinator(int id) {
		this.id = id;
	}

	public HolonCoordinator(int id, Holon holon, LatLng latLng, String name,
			Set holonObjects) {
		this.id = id;
		this.holon = holon;
		this.latLng = latLng;
		this.name = name;
		this.holonObjects = holonObjects;
	}

	public Holon getHolon() {
		return this.holon;
	}

	public Set getHolonObjects() {
		return this.holonObjects;
	}

	public int getId() {
		return this.id;
	}

	public LatLng getLatLng() {
		return this.latLng;
	}

	public String getName() {
		return this.name;
	}

	public void setHolon(Holon holon) {
		this.holon = holon;
	}

	public void setHolonObjects(Set holonObjects) {
		this.holonObjects = holonObjects;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setLatLng(LatLng latLng) {
		this.latLng = latLng;
	}

	public void setName(String name) {
		this.name = name;
	}

}
