package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Holon generated by hbm2java
 */
public class Holon implements java.io.Serializable {

	private int id;
	private LatLng latLng;
	private String name;
	private Integer radius;
	private Set holonObjects = new HashSet(0);
	private Set holonCoordinators = new HashSet(0);

	public Holon() {
	}

	public Holon(int id) {
		this.id = id;
	}

	public Holon(int id, LatLng latLng, String name, Integer radius,
			Set holonObjects, Set holonCoordinators) {
		this.id = id;
		this.latLng = latLng;
		this.name = name;
		this.radius = radius;
		this.holonObjects = holonObjects;
		this.holonCoordinators = holonCoordinators;
	}

	public Set getHolonCoordinators() {
		return this.holonCoordinators;
	}

	public Set getHolonObjects() {
		return this.holonObjects;
	}

	public int getId() {
		return this.id;
	}

	public LatLng getLatLng() {
		return this.latLng;
	}

	public String getName() {
		return this.name;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setHolonCoordinators(Set holonCoordinators) {
		this.holonCoordinators = holonCoordinators;
	}

	public void setHolonObjects(Set holonObjects) {
		this.holonObjects = holonObjects;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setLatLng(LatLng latLng) {
		this.latLng = latLng;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

}
