package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

/**
 * HolonElement generated by hbm2java
 */
public class HolonElement implements java.io.Serializable {

	private int id;
	private HolonElementState holonElementState;
	private HolonElementType holonElementType;
	private HolonManager holonManager;
	private HolonObject holonObject;
	private String usage;
	private Integer maxCapacity;
	private Integer minCapacity;
	private Integer currentCapacity;
	private Boolean currentEnergyStatus;
	private byte[] history;

	public HolonElement() {
	}

	public HolonElement(int id) {
		this.id = id;
	}

	public HolonElement(int id, HolonElementState holonElementState,
			HolonElementType holonElementType, HolonManager holonManager,
			HolonObject holonObject, String usage, Integer maxCapacity,
			Integer minCapacity, Integer currentCapacity,
			Boolean currentEnergyStatus, byte[] history) {
		this.id = id;
		this.holonElementState = holonElementState;
		this.holonElementType = holonElementType;
		this.holonManager = holonManager;
		this.holonObject = holonObject;
		this.usage = usage;
		this.maxCapacity = maxCapacity;
		this.minCapacity = minCapacity;
		this.currentCapacity = currentCapacity;
		this.currentEnergyStatus = currentEnergyStatus;
		this.history = history;
	}

	public Integer getCurrentCapacity() {
		return this.currentCapacity;
	}

	public Boolean getCurrentEnergyStatus() {
		return this.currentEnergyStatus;
	}

	public byte[] getHistory() {
		return this.history;
	}

	public HolonElementState getHolonElementState() {
		return this.holonElementState;
	}

	public HolonElementType getHolonElementType() {
		return this.holonElementType;
	}

	public HolonManager getHolonManager() {
		return this.holonManager;
	}

	public HolonObject getHolonObject() {
		return this.holonObject;
	}

	public int getId() {
		return this.id;
	}

	public Integer getMaxCapacity() {
		return this.maxCapacity;
	}

	public Integer getMinCapacity() {
		return this.minCapacity;
	}

	public String getUsage() {
		return this.usage;
	}

	public void setCurrentCapacity(Integer currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public void setCurrentEnergyStatus(Boolean currentEnergyStatus) {
		this.currentEnergyStatus = currentEnergyStatus;
	}

	public void setHistory(byte[] history) {
		this.history = history;
	}

	public void setHolonElementState(HolonElementState holonElementState) {
		this.holonElementState = holonElementState;
	}

	public void setHolonElementType(HolonElementType holonElementType) {
		this.holonElementType = holonElementType;
	}

	public void setHolonManager(HolonManager holonManager) {
		this.holonManager = holonManager;
	}

	public void setHolonObject(HolonObject holonObject) {
		this.holonObject = holonObject;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setMaxCapacity(Integer maxCapacity) {
		this.maxCapacity = maxCapacity;
	}

	public void setMinCapacity(Integer minCapacity) {
		this.minCapacity = minCapacity;
	}

	public void setUsage(String usage) {
		this.usage = usage;
	}

}
