package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HolonElementType generated by hbm2java
 */
public class HolonElementType implements java.io.Serializable {

	private int id;
	private String name;
	private Set holonElements = new HashSet(0);

	public HolonElementType() {
	}

	public HolonElementType(int id) {
		this.id = id;
	}

	public HolonElementType(int id, String name, Set holonElements) {
		this.id = id;
		this.name = name;
		this.holonElements = holonElements;
	}

	public Set getHolonElements() {
		return this.holonElements;
	}

	public int getId() {
		return this.id;
	}

	public String getName() {
		return this.name;
	}

	public void setHolonElements(Set holonElements) {
		this.holonElements = holonElements;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

}
