package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * HolonObjectType generated by hbm2java
 */
public class HolonObjectType implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set holonObjects = new HashSet(0);

	public HolonObjectType() {
	}

	public HolonObjectType(String name, Set holonObjects) {
		this.name = name;
		this.holonObjects = holonObjects;
	}

	public Set getHolonObjects() {
		return this.holonObjects;
	}

	public Integer getId() {
		return this.id;
	}

	public String getName() {
		return this.name;
	}

	public void setHolonObjects(Set holonObjects) {
		this.holonObjects = holonObjects;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

}
