package com.htc.hibernate.pojo;

// Generated 1 Jul, 2015 9:39:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Holon generated by hbm2java
 */
public class Holon implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private LatLng latLng;
	private String name;
	private Integer radius;
	private String color;
	private Set<?> holonCoordinators = new HashSet<Object>(0);

	public Holon() {
	}

	public Holon(int id) {
		this.id = id;
	}

	public Holon(int id, LatLng latLng, String name, Integer radius,
			String color, Set<?> holonCoordinators) {
		this.id = id;
		this.latLng = latLng;
		this.name = name;
		this.radius = radius;
		this.color = color;
		this.holonCoordinators = holonCoordinators;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public LatLng getLatLng() {
		return this.latLng;
	}

	public void setLatLng(LatLng latLng) {
		this.latLng = latLng;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set<?> getHolonCoordinators() {
		return this.holonCoordinators;
	}

	public void setHolonCoordinators(Set<?> holonCoordinators) {
		this.holonCoordinators = holonCoordinators;
	}

}
