package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * LatLng generated by hbm2java
 */
public class LatLng implements java.io.Serializable {

	private Integer id;
	private double lat_ne;
	private double lng_ne;
	private double lat_sw;
	private double lng_sw;
	private Set holons = new HashSet(0);
	private Set holonCoordinators = new HashSet(0);
	private Set holonObjects = new HashSet(0);
	private Set powerLinesForSource = new HashSet(0);
	private Set powerLineNodes = new HashSet(0);
	private Set powerLinesForDestination = new HashSet(0);
	private Set powerSwitches = new HashSet(0);

	public LatLng() {
	}

	public LatLng(double lat_ne, double lng_ne, double lat_sw, double lng_sw) {
		this.lat_ne = lat_ne;
		this.lng_ne = lng_ne;
		this.lat_sw = lat_sw;
		this.lng_sw = lng_sw;
	}

	public LatLng(double lat_ne, double lng_ne,double lat_sw, double lng_sw, Set holons, Set holonCoordinators,
			Set holonObjects, Set powerLinesForSource, Set powerLineNodes,
			Set powerLinesForDestination, Set powerSwitches) {
		this.lat_ne = lat_ne;
		this.lng_ne = lng_ne;
		this.lat_sw = lat_sw;
		this.lng_sw = lng_sw;
		this.holons = holons;
		this.holonCoordinators = holonCoordinators;
		this.holonObjects = holonObjects;
		this.powerLinesForSource = powerLinesForSource;
		this.powerLineNodes = powerLineNodes;
		this.powerLinesForDestination = powerLinesForDestination;
		this.powerSwitches = powerSwitches;
	}

	public Set getHolonCoordinators() {
		return this.holonCoordinators;
	}

	public Set getHolonObjects() {
		return this.holonObjects;
	}

	public Set getHolons() {
		return this.holons;
	}

	public Integer getId() {
		return this.id;
	}

	public Set getPowerLineNodes() {
		return this.powerLineNodes;
	}

	public Set getPowerLinesForDestination() {
		return this.powerLinesForDestination;
	}

	public Set getPowerLinesForSource() {
		return this.powerLinesForSource;
	}

	public Set getPowerSwitches() {
		return this.powerSwitches;
	}

	public double getLat_ne() {
		return lat_ne;
	}

	public double getLng_ne() {
		return lng_ne;
	}

	public double getLat_sw() {
		return lat_sw;
	}

	public double getLng_sw() {
		return lng_sw;
	}

	public void setHolonCoordinators(Set holonCoordinators) {
		this.holonCoordinators = holonCoordinators;
	}

	public void setHolonObjects(Set holonObjects) {
		this.holonObjects = holonObjects;
	}

	public void setHolons(Set holons) {
		this.holons = holons;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public void setPowerLineNodes(Set powerLineNodes) {
		this.powerLineNodes = powerLineNodes;
	}

	public void setPowerLinesForDestination(Set powerLinesForDestination) {
		this.powerLinesForDestination = powerLinesForDestination;
	}

	public void setPowerLinesForSource(Set powerLinesForSource) {
		this.powerLinesForSource = powerLinesForSource;
	}

	public void setPowerSwitches(Set powerSwitches) {
		this.powerSwitches = powerSwitches;
	}

	public void setLat_ne(double lat_ne) {
		this.lat_ne = lat_ne;
	}

	public void setLng_ne(double lng_ne) {
		this.lng_ne = lng_ne;
	}

	public void setLat_sw(double lat_sw) {
		this.lat_sw = lat_sw;
	}

	public void setLng_sw(double lng_sw) {
		this.lng_sw = lng_sw;
	}
	



}
