package com.htc.hibernate.pojo;
// Generated 16 Aug, 2015 3:28:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PowerSource generated by hbm2java
 */
public class PowerSource implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int id;
	private HolonCoordinator holonCoordinator;
	private LatLng center;
	private String name;
	private Integer minProduction;
	private Integer maxProduction;
	private Integer currentProduction;
	private Double radius;
	private Boolean status;
	private Integer flexibility;
	private Set<?> powerLines = new HashSet<Object>(0);

	public PowerSource() {
	}

	public PowerSource(int id) {
		this.id = id;
	}

	public PowerSource(int id, HolonCoordinator holonCoordinator,
			LatLng center, String name, Integer minProduction,
			Integer maxProduction, Integer currentProduction, Double radius,
			Boolean status, Integer flexibility, Set<?> powerLines) {
		this.id = id;
		this.holonCoordinator = holonCoordinator;
		this.setCenter(center);
		this.name = name;
		this.minProduction = minProduction;
		this.maxProduction = maxProduction;
		this.currentProduction = currentProduction;
		this.radius = radius;
		this.status = status;
		this.flexibility = flexibility;
		this.powerLines = powerLines;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public HolonCoordinator getHolonCoordinator() {
		return this.holonCoordinator;
	}

	public void setHolonCoordinator(HolonCoordinator holonCoordinator) {
		this.holonCoordinator = holonCoordinator;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMinProduction() {
		return this.minProduction;
	}

	public void setMinProduction(Integer minProduction) {
		this.minProduction = minProduction;
	}

	public Integer getMaxProduction() {
		return this.maxProduction;
	}

	public void setMaxProduction(Integer maxProduction) {
		this.maxProduction = maxProduction;
	}

	public Integer getCurrentProduction() {
		return this.currentProduction;
	}

	public void setCurrentProduction(Integer currentProduction) {
		this.currentProduction = currentProduction;
	}

	public Double getRadius() {
		return this.radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<?> getPowerLines() {
		return this.powerLines;
	}

	public void setPowerLines(Set<?> powerLines) {
		this.powerLines = powerLines;
	}

	public LatLng getCenter() {
		return center;
	}

	public void setCenter(LatLng center) {
		this.center = center;
	}

	public Integer getFlexibility() {
		return flexibility;
	}

	public void setFlexibility(Integer flexibility) {
		this.flexibility = flexibility;
	}

}
