package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

/**
 * PowerLineNode generated by hbm2java
 */
public class PowerLineNode implements java.io.Serializable {

	private int id;
	private LatLng latLng;
	private String name;

	public PowerLineNode() {
	}

	public PowerLineNode(int id) {
		this.id = id;
	}

	public PowerLineNode(int id, LatLng latLng, String name) {
		this.id = id;
		this.latLng = latLng;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public LatLng getLatLng() {
		return this.latLng;
	}

	public String getName() {
		return this.name;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setLatLng(LatLng latLng) {
		this.latLng = latLng;
	}

	public void setName(String name) {
		this.name = name;
	}

}
