package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

/**
 * PowerSwitch generated by hbm2java
 */
public class PowerSwitch implements java.io.Serializable {

	private int id;
	private LatLng latLng;
	private PowerLine powerLine;
	private Boolean status;
	private String belongsTo;
	private int holonObjectId;
	private int powerLineId;

	public PowerSwitch() {
	}

	public PowerSwitch(int id, LatLng latLng) {
		this.id = id;
		this.latLng = latLng;
	}

	public PowerSwitch(int id, LatLng latLng, PowerLine powerLine,
			Boolean status, String belongsTo) {
		this.id = id;
		this.latLng = latLng;
		this.powerLine = powerLine;
		this.status = status;
		this.belongsTo = belongsTo;
	}

	public String getBelongsTo() {
		return this.belongsTo;
	}

	public int getId() {
		return this.id;
	}

	public LatLng getLatLng() {
		return this.latLng;
	}

	public PowerLine getPowerLine() {
		return this.powerLine;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setBelongsTo(String belongsTo) {
		this.belongsTo = belongsTo;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setLatLng(LatLng latLng) {
		this.latLng = latLng;
	}

	public void setPowerLine(PowerLine powerLine) {
		this.powerLine = powerLine;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public int getHolonObjectId() {
		return holonObjectId;
	}

	public void setHolonObjectId(int holonObjectId) {
		this.holonObjectId = holonObjectId;
	}

	public int getPowerLineId() {
		return powerLineId;
	}

	public void setPowerLineId(int powerLineId) {
		this.powerLineId = powerLineId;
	}

}
