package com.htc.hibernate.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * PowerSource generated by hbm2java
 */
public class PowerSource implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Integer minProduction;
	private Integer maxProduction;
	private Integer currentProduction;
	private LatLng centre;
	private double radius;
	private boolean status;
	private HolonCoordinator holonCoordinator;
	private PowerLine powerLine;
	
	private Set<?> powerLines = new HashSet<Object>(0);

	public PowerSource() {
	}

	public PowerSource(int id) {
		this.id = id;
	}

	public PowerSource(int id, String name, Integer minProduction, Integer maxProduction,boolean status,
			Integer currentProduction, LatLng centre,double radius, HolonCoordinator holonCoordinator, PowerLine powerLine,
			Set<?> powerLines) {
		this.id = id;
		this.name = name;
		this.minProduction = minProduction;
		this.maxProduction = maxProduction;
		this.currentProduction = currentProduction;
		this.centre = centre;
		this.radius = radius;
		this.status=status;
		this.holonCoordinator = holonCoordinator;
		this.powerLine = powerLine;
		this.powerLines = powerLines;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public LatLng getCentre() {
		return centre;
	}

	public void setCentre(LatLng centre) {
		this.centre = centre;
	}

	public HolonCoordinator getHolonCoordinator() {
		return holonCoordinator;
	}

	public void setHolonCoordinator(HolonCoordinator holonCoordinator) {
		this.holonCoordinator = holonCoordinator;
	}

	public PowerLine getPowerLine() {
		return powerLine;
	}

	public void setPowerLine(PowerLine powerLine) {
		this.powerLine = powerLine;
	}

	public Integer getMinProduction() {
		return this.minProduction;
	}

	public void setMinProduction(Integer minProduction) {
		this.minProduction = minProduction;
	}

	public Integer getMaxProduction() {
		return this.maxProduction;
	}

	public void setMaxProduction(Integer maxProduction) {
		this.maxProduction = maxProduction;
	}

	public Integer getCurrentProduction() {
		return this.currentProduction;
	}

	public void setCurrentProduction(Integer currentProduction) {
		this.currentProduction = currentProduction;
	}

	public Set<?> getPowerLines() {
		return this.powerLines;
	}

	public void setPowerLines(Set<?> powerLines) {
		this.powerLines = powerLines;
	}

	public double getRadius() {
		return radius;
	}

	public void setRadius(double radius) {
		this.radius = radius;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
