package com.htc.hibernate.pojo;

// default package
// Generated 19 Jun, 2015 7:20:49 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PowerLine generated by hbm2java
 */
public class PowerLine implements java.io.Serializable {

	private Integer id;
	private LatLng latLngBySource;
	private LatLng latLngByDestination;
	private String type;
	private int currentCapacity;
	private int maximumCapacity;
	private boolean isConnected;
	private String reasonDown;
	private Set powerSwitches = new HashSet(0);

	public PowerLine() {
	}

	public PowerLine(LatLng latLngBySource, LatLng latLngByDestination,
			String type, int currentCapacity, int maximumCapacity,
			boolean isConnected, String reasonDown, Set powerSwitches) {
		this.latLngBySource = latLngBySource;
		this.latLngByDestination = latLngByDestination;
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
		this.reasonDown = reasonDown;
		this.powerSwitches = powerSwitches;
	}

	public PowerLine(String type, int currentCapacity, int maximumCapacity,
			boolean isConnected) {
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
	}

	public int getCurrentCapacity() {
		return this.currentCapacity;
	}

	public Integer getId() {
		return this.id;
	}

	public LatLng getLatLngByDestination() {
		return this.latLngByDestination;
	}

	public LatLng getLatLngBySource() {
		return this.latLngBySource;
	}

	public int getMaximumCapacity() {
		return this.maximumCapacity;
	}

	public Set getPowerSwitches() {
		return this.powerSwitches;
	}

	public String getReasonDown() {
		return this.reasonDown;
	}

	public String getType() {
		return this.type;
	}

	public boolean isIsConnected() {
		return this.isConnected;
	}

	public void setCurrentCapacity(int currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setIsConnected(boolean isConnected) {
		this.isConnected = isConnected;
	}

	public void setLatLngByDestination(LatLng latLngByDestination) {
		this.latLngByDestination = latLngByDestination;
	}

	public void setLatLngBySource(LatLng latLngBySource) {
		this.latLngBySource = latLngBySource;
	}

	public void setMaximumCapacity(int maximumCapacity) {
		this.maximumCapacity = maximumCapacity;
	}

	public void setPowerSwitches(Set powerSwitches) {
		this.powerSwitches = powerSwitches;
	}

	public void setReasonDown(String reasonDown) {
		this.reasonDown = reasonDown;
	}

	public void setType(String type) {
		this.type = type;
	}

}
