package com.htc.hibernate.pojo;

import java.util.HashSet;
import java.util.Set;

/**
 * PowerLine generated by hbm2java
 */
public class PowerLine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private LatLng latLngBySource;
	private LatLng latLngByDestination;
	private PowerLine powerLine;
	private PowerSource powerSource;
	private String type;
	private int currentCapacity;
	private int maximumCapacity;
	private boolean isConnected;
	private String reasonDown;
	private Set<?> powerLines = new HashSet<Object>(0);
	private Set<?> holonObjects = new HashSet<Object>(0);
	private Set<?> powerSwitchesA = new HashSet<Object>(0);
	private Set<?> powerSwitchesB = new HashSet<Object>(0);

	public PowerLine() {
	}
	
	public PowerLine(int id) {
		this.id=id;
	}
	
	public PowerLine(String type, int currentCapacity, int maximumCapacity,
			boolean isConnected) {
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
	}

	public PowerLine(LatLng latLngBySource, LatLng latLngByDestination,
			PowerLine powerLine, PowerSource powerSource, String type,
			int currentCapacity, int maximumCapacity, boolean isConnected,
			String reasonDown, Set<?> powerLines, Set<?> holonObjects,
			Set<?> powerSwitchesA,Set<?> powerSwitchesB) {
		this.latLngBySource = latLngBySource;
		this.latLngByDestination = latLngByDestination;
		this.powerLine = powerLine;
		this.powerSource = powerSource;
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
		this.reasonDown = reasonDown;
		this.powerLines = powerLines;
		this.holonObjects = holonObjects;
		this.powerSwitchesA = powerSwitchesA;
		this.setPowerSwitchesB(powerSwitchesB);
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LatLng getLatLngBySource() {
		return this.latLngBySource;
	}

	public void setLatLngBySource(LatLng latLngBySource) {
		this.latLngBySource = latLngBySource;
	}

	public LatLng getLatLngByDestination() {
		return this.latLngByDestination;
	}

	public void setLatLngByDestination(LatLng latLngByDestination) {
		this.latLngByDestination = latLngByDestination;
	}

	public PowerLine getPowerLine() {
		return this.powerLine;
	}

	public void setPowerLine(PowerLine powerLine) {
		this.powerLine = powerLine;
	}

	public PowerSource getPowerSource() {
		return this.powerSource;
	}

	public void setPowerSource(PowerSource powerSource) {
		this.powerSource = powerSource;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getCurrentCapacity() {
		return this.currentCapacity;
	}

	public void setCurrentCapacity(int currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public int getMaximumCapacity() {
		return this.maximumCapacity;
	}

	public void setMaximumCapacity(int maximumCapacity) {
		this.maximumCapacity = maximumCapacity;
	}

	public boolean isIsConnected() {
		return this.isConnected;
	}

	public void setIsConnected(boolean isConnected) {
		this.isConnected = isConnected;
	}

	public String getReasonDown() {
		return this.reasonDown;
	}

	public void setReasonDown(String reasonDown) {
		this.reasonDown = reasonDown;
	}

	public Set<?> getPowerLines() {
		return this.powerLines;
	}

	public void setPowerLines(Set<?> powerLines) {
		this.powerLines = powerLines;
	}

	public Set<?> getHolonObjects() {
		return this.holonObjects;
	}

	public void setHolonObjects(Set<?> holonObjects) {
		this.holonObjects = holonObjects;
	}

	public Set<?> getPowerSwitchesA() {
		return this.powerSwitchesA;
	}

	public void setPowerSwitchesA(Set<?> powerSwitchesA) {
		this.powerSwitchesA = powerSwitchesA;
	}

	public Set<?> getPowerSwitchesB() {
		return powerSwitchesB;
	}

	public void setPowerSwitchesB(Set<?> powerSwitchesB) {
		this.powerSwitchesB = powerSwitchesB;
	}

}
