package com.htc.hibernate.pojo;
// Generated 1 Jul, 2015 9:39:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * PowerLine generated by hbm2java
 */
public class PowerLine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private LatLng latLngBySource;
	private LatLng latLngByDestination;
	private PowerSource powerSource;
	private String type;
	private int currentCapacity;
	private int maximumCapacity;
	private boolean isConnected;
	private String reasonDown;
	private Set<?> powerSwitches = new HashSet<Object>(0);

	public PowerLine() {
	}

	public PowerLine(String type, int currentCapacity, int maximumCapacity,
			boolean isConnected) {
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
	}

	public PowerLine(LatLng latLngBySource, LatLng latLngByDestination,
			PowerSource powerSource, String type, int currentCapacity,
			int maximumCapacity, boolean isConnected, String reasonDown,
			Set<?> powerSwitches) {
		this.latLngBySource = latLngBySource;
		this.latLngByDestination = latLngByDestination;
		this.powerSource = powerSource;
		this.type = type;
		this.currentCapacity = currentCapacity;
		this.maximumCapacity = maximumCapacity;
		this.isConnected = isConnected;
		this.reasonDown = reasonDown;
		this.powerSwitches = powerSwitches;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LatLng getLatLngBySource() {
		return this.latLngBySource;
	}

	public void setLatLngBySource(LatLng latLngBySource) {
		this.latLngBySource = latLngBySource;
	}

	public LatLng getLatLngByDestination() {
		return this.latLngByDestination;
	}

	public void setLatLngByDestination(LatLng latLngByDestination) {
		this.latLngByDestination = latLngByDestination;
	}

	public PowerSource getPowerSource() {
		return this.powerSource;
	}

	public void setPowerSource(PowerSource powerSource) {
		this.powerSource = powerSource;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getCurrentCapacity() {
		return this.currentCapacity;
	}

	public void setCurrentCapacity(int currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	public int getMaximumCapacity() {
		return this.maximumCapacity;
	}

	public void setMaximumCapacity(int maximumCapacity) {
		this.maximumCapacity = maximumCapacity;
	}

	public boolean isIsConnected() {
		return this.isConnected;
	}

	public void setIsConnected(boolean isConnected) {
		this.isConnected = isConnected;
	}

	public String getReasonDown() {
		return this.reasonDown;
	}

	public void setReasonDown(String reasonDown) {
		this.reasonDown = reasonDown;
	}

	public Set<?> getPowerSwitches() {
		return this.powerSwitches;
	}

	public void setPowerSwitches(Set<?> powerSwitches) {
		this.powerSwitches = powerSwitches;
	}

}
